trigger:
- master
- vs*
- exp/*

# If defined here, these values are not overrideable
# Once they exist, we should define these as "runtime parameters"
# https://github.com/Microsoft/azure-pipelines-yaml/pull/129
# variables:
#   SignType: real
#   SkipApplyOptimizationData: false

variables:
  - name: SourceBranch
    value: $(IbcSourceBranchName)
  - ${{ if and(eq(variables['Build.SourceBranchName'], variables['IbcSourceBranchName']), startsWith(variables['Build.SourceBranch'], 'refs/heads/exp/')) }}:
    # For exp branches, get data from master unless explicitly specified
    - name: SourceBranch
      value: master
  - name: _DotNetArtifactsCategory
    value: .NETCore
  - name: _DotNetValidationArtifactsCategory
    value: .NETCoreValidation

stages:
- stage: build
  displayName: Build

  jobs:
  - job: Windows_NT
    pool:
      name: VSEng-MicroBuildVS2019
      demands:
      - agent.os -equals Windows_NT

    timeoutInMinutes: 180

    variables:
    - group: DotNet-Blob-Feed
    - group: DotNet-Symbol-Publish
    - group: Publish-Build-Assets
    - name: TeamName
      value: MSBuild
    - name: VisualStudio.MajorVersion
      value: 16
    - name: VisualStudio.ChannelName
      value: 'int.main'
    - name: VisualStudio.DropName
      value: Products/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)

    steps:
    - script: eng/CIBuild.cmd
                -configuration $(BuildConfiguration)
                -officialBuildId $(Build.BuildNumber)
                -officialSkipApplyOptimizationData $(SkipApplyOptimizationData)
                /p:RepositoryName=$(Build.Repository.Name)
                /p:VisualStudioIbcSourceBranchName=$(SourceBranch)
                /p:VisualStudioDropAccessToken=$(System.AccessToken)
                /p:VisualStudioDropName=$(VisualStudio.DropName)
                /p:DotNetSignType=$(SignType)
                /p:DotNetPublishToBlobFeed=true
                /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1)
                /p:DotNetPublishBlobFeedUrl=https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
                /p:PublishToSymbolServer=true
                /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
                /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
                /p:TeamName=MSBuild
                /p:DotNetPublishUsingPipelines=true
      displayName: Build b.sbn=${{ variables['Build.SourceBranchName'] }} sb=${{ variables['IbcSourceBranchName'] }} eq=${{ eq(variables['Build.SourceBranchName'], variables['SourceBranch']) }} sw=${{startsWith(variables['Build.SourceBranch'], 'refs/heads/exp/')}} and=${{ and(eq(variables['Build.SourceBranchName'], variables['SourceBranch']), startsWith(variables['Build.SourceBranchName'], 'refs/heads/exp/')) }}
      condition: succeeded()
