trigger:
- master
- exp/*
- vs*

phases:
- phase: FullOnWindows
  displayName: "Build and test on Windows using full MSBuild"
  queue: 'Hosted VS2017'
  steps:
  - task: BatchScript@1
    displayName: VsDevCmd
    inputs:
      filename: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat'
      modifyEnvironment: true
  - task: BatchScript@1
    displayName: cibuild.cmd
    inputs:
      filename: 'build/cibuild.cmd'
  - task: PublishTestResults@2
    displayName: Publish .NET Framework Test Results
    inputs:
      testRunTitle: 'Windows-on-full Full Framework'
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests_net472*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish .NET Core 2.1 Test Results
    inputs:
      testRunTitle: 'Windows-on-full .NET Core 2.1'
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests_netcoreapp2.1*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/Debug/log'
      ArtifactName: 'FullOnWindows build logs'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs/TestResults'
    inputs:
      PathtoPublish: 'artifacts/2/Debug/log/TestResults'
      ArtifactName: 'FullOnWindows test logs'
    condition: succeededOrFailed()

- phase: FullReleaseOnWindows
  displayName: "Build and test Release on Windows using full MSBuild"
  queue: 'Hosted VS2017'
  steps:
  - task: BatchScript@1
    displayName: VsDevCmd
    inputs:
      filename: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat'
      modifyEnvironment: true
  - task: BatchScript@1
    displayName: cibuild.cmd
    inputs:
      filename: 'build/cibuild.cmd'
      arguments: '-configuration Release'
  - task: PublishTestResults@2
    displayName: Publish .NET Framework Test Results
    inputs:
      testRunTitle: 'Windows-on-full Release Full Framework'
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests_net472*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish .NET Core 2.1 Test Results
    inputs:
      testRunTitle: 'Windows-on-full Release .NET Core 2.1'
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests_netcoreapp2.1*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/Release/log'
      ArtifactName: 'FullOnWindows Release build logs'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs/TestResults'
    inputs:
      PathtoPublish: 'artifacts/2/Release/log/TestResults'
      ArtifactName: 'FullOnWindows Release test logs'
    condition: succeededOrFailed()

- phase: CoreOnWindows
  displayName: "Build and test on Windows using .NET Core MSBuild"
  queue: 'Hosted VS2017'
  steps:
  - task: BatchScript@1
    displayName: VsDevCmd
    inputs:
      filename: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat'
      modifyEnvironment: true
  - task: BatchScript@1
    displayName: cibuild.cmd
    inputs:
      filename: 'build/cibuild.cmd'
      arguments: '-hostType Core'
  - task: PublishTestResults@2
    displayName: Publish .NET Framework Test Results
    inputs:
      testRunTitle: 'Windows-on-core Full Framework'
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests_net472*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish .NET Core 2.1 Test Results
    inputs:
      testRunTitle: 'Windows-on-core .NET Core 2.1'
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests_netcoreapp2.1*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/Debug/log'
      ArtifactName: 'CoreOnWindows build logs'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs/TestResults'
    inputs:
      PathtoPublish: 'artifacts/2/Debug/log/TestResults'
      ArtifactName: 'CoreOnWindows test logs'
    condition: succeededOrFailed()

- phase: CoreOnLinux
  displayName: "Build and test on Linux using .NET Core MSBuild"
  queue: 'Hosted Ubuntu 1604'
  steps:
  - bash: . 'build/cibuild.sh'
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish .NET Core 2.1 Test Results
    inputs:
      testRunTitle: 'Linux .NET Core 2.1'
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests_netcoreapp2.1*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/Debug/log'
      ArtifactName: 'CoreOnLinux build logs'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs/TestResults'
    inputs:
      PathtoPublish: 'artifacts/2/Debug/log/TestResults'
      ArtifactName: 'CoreOnLinux test logs'
    condition: succeededOrFailed()

- phase: CoreOnMac
  displayName: "Build and test on macOS using .NET Core MSBuild"
  queue: 'Hosted macOS'
  steps:
  - bash: . 'build/cibuild.sh'
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish .NET Core 2.1 Test Results
    inputs:
      testRunTitle: 'macOS .NET Core 2.1'
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests_netcoreapp2.1*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/Debug/log'
      ArtifactName: 'CoreOnMac build logs'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs/TestResults'
    inputs:
      PathtoPublish: 'artifacts/2/Debug/log/TestResults'
      ArtifactName: 'CoreOnMac test logs'
    condition: succeededOrFailed()

