trigger:
- master
- vs*
- exp/*

# If defined here, these values are not overrideable
# Once they exist, we should define these as "runtime parameters"
# https://github.com/Microsoft/azure-pipelines-yaml/pull/129
# variables:
#   SignType: real
#   SkipApplyOptimizationData: false

variables:
  - name: SourceBranch
    value: $(IbcSourceBranchName)
  - ${{ if and(eq(variables.Build.SourceBranchName, variables.IbcSourceBranchName), startsWith(variables['Build.SourceBranch'], 'refs/heads/exp/')) }}:
    # For exp branches, get data from master unless explicitly specified
    - name: SourceBranch
      value: master


stages:
- stage: build
  displayName: Build

  jobs:
  - job: Windows_NT
    pool:
      name: VSEng-MicroBuildVS2019
      demands:
      - agent.os -equals Windows_NT

    timeoutInMinutes: 180

    steps:
    - script: echo final=$(SourceBranch)
      displayName: Build b.sbn="${{ variables['Build.SourceBranchName'] }}" ibc="${{variables['IbcSourceBranchName']}}" ibcq="${{'$(IbcSourceBranchName)'}}" eq="${{eq('$(Build.SourceBranchName)', '$(IbcSourceBranchName)')}}" sb="${{variables['SourceBranch']}}"
      condition: succeeded()
    - script: echo eq(variables.Build.SourceBranchName, variables.IbcSourceBranchName) evals to ${{eq(variables.Build.SourceBranchName, variables.IbcSourceBranchName)}}
      displayName: evals to ${{ eq(variables.Build.SourceBranchName, variables.IbcSourceBranchName) }}
      condition: succeeded()
