trigger:
- master
- vs*
- exp/*

# If defined here, these values are not overrideable
# Once they exist, we should define these as "runtime parameters"
# https://github.com/Microsoft/azure-pipelines-yaml/pull/129
# variables:
#   SignType: real
#   SkipApplyOptimizationData: false

variables:
  - name: SourceBranch
    value: $(IbcSourceBranchName)
  - ${{ if startsWith(variables['IbcSourceBranchName'], variables['Build.SourceBranchName']) }}:
    # For exp branches, get data from master unless explicitly specified
    - name: SourceBranch
      value: master
  - name: _DotNetArtifactsCategory
    value: .NETCore
  - name: _DotNetValidationArtifactsCategory
    value: .NETCoreValidation

stages:
- stage: build
  displayName: Build

  jobs:
  - job: Windows_NT
    pool:
      name: VSEng-MicroBuildVS2019
      demands:
      - agent.os -equals Windows_NT

    timeoutInMinutes: 180

    variables:
    - group: DotNet-Blob-Feed
    - group: DotNet-Symbol-Publish
    - group: Publish-Build-Assets
    - name: TeamName
      value: MSBuild
    - name: VisualStudio.MajorVersion
      value: 16
    - name: VisualStudio.ChannelName
      value: 'int.main'
    - name: VisualStudio.DropName
      value: Products/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)

    steps:
    - script: echo BSBN $(Build.SourceBranchName) IBCSBN $(IbcSourceBranchName) SourceBranch $(SourceBranch)
      displayName: Build b.sbn=${{ variables['Build.SourceBranchName'] }}
      condition: succeeded()
