# Update the SDK version stored in eng/Versions.props that must match
# the one Arcade updates in global.json

name: Sync SDK version

on:
  push:
    paths:
    - 'global.json'
    branches:
    - 'darc*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Copy global.json SDK to Versions
      run: |
        sed -i "s/<DotNetCliVersion>[^<]*<\/DotNetCliVersion>/<DotNetCliVersion>$(jq -r '.tools.dotnet' global.json)<\/DotNetCliVersion>/" eng/Versions.props

    - name: Check for modified files
      id: git-check
      run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

    - name: Push if necessary
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name 'MSBuild Automation'
        git config --global user.email 'dotnet-bot@users.noreply.github.com'

        git add eng/Versions.props

        git commit -m "Sync .NET SDK version to $(jq -r '.tools.dotnet' global.json)"

        git push
